---
- hosts: appserver
  remote_user: rajarshi
  tasks:
  - name: Check container
    community.general.docker_container:
      name: test_
      state: present
      image: ubuntu
      container_default_behavior: compatibility